bayke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baykeshop.urls')),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

baykeshop/api/auth/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # 获取token post
    path("token/", views.TokenObtainPairView.as_view(), name="token"),
    # 刷新token post
    path("refresh/", views.TokenRefreshView.as_view(), name="refresh"),
    # 验证token post 
    path("verify/", views.TokenVerifyView.as_view(), name="verify"),
    # 退出 post
    path("logout/", views.LogoutView.as_view(), name="logout"),
    # 获取邮箱验证码
    path('obtain/code/', views.BaykeVerifyCodeObtainAPIView.as_view(), name='obtain-code'),
    # 效验邮箱验证码 post
    path('check/code/', views.BaykeVerifyCodeCheckAPIView.as_view(), name='check-code'),
    # 注册接口 post
    path("register/", views.BaykeUserRegisterAPIView.as_view(), name="register-api"),
    # 修改自己的密码 post
    path("user/changepassword/", views.UpdateUserPasswordView.as_view(), name="user-changepassword"),
    # 修改指定用户的密码 post
    path("owner/changepassword/", views.UpdateOwnerPasswordView.as_view(), name="owner-changepassword"),
]

baykeshop/api/shop/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from . import viewsets

router = DefaultRouter()

router.register('category', viewsets.BaykeShopCategoryViewSet, basename='category')

router.register('brand', viewsets.BaykeshopBrandViewSet, basename='brand')

router.register('spu', viewsets.BaykeShopSPUViewSet, basename='spu')

router.register('sku', viewsets.BaykeShopSKUViewSet, basename='sku')

router.register('spec', viewsets.BaykeShopSpecViewSet, basename='spec')

router.register('specvalue', viewsets.BaykeShopSpecValueViewSet, basename='specvalue')

router.register('order', viewsets.BaykeShopOrderViewSet, basename='order')

router.register('cart', viewsets.BaykeShopCartViewSet, basename='cart')

router.register('address', viewsets.BaykeAddressViewSet, basename='address')

router.register('banner', viewsets.BaykeShopBannerViewSet, basename='banner')

urlpatterns = [
    # 创建商品
    path('spu/create/', viewsets.BaykeShopSPUCreateOrUpdateAPIView.as_view(), name='spu_create'),
    # 余额充值
    path('balance/create/', viewsets.BalanceRechargeAPIView.as_view(), name='user_balance_create'),
    
    *router.urls
]

baykeshop/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('shop/', include(('baykeshop.api.shop.urls', 'baykeshop'), namespace="shop_api")),
    path('auth/', include(('baykeshop.api.auth.urls', 'baykeshop'), namespace='auth_api')),
    path('badmin/', include(('baykeshop.api.badmin.urls', 'baykeshop'), namespace='badmin_api')),
    path('comment/', include(('baykeshop.api.comment.urls', 'baykeshop'), namespace='comment_api')),
]

baykeshop/apps/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name="home"),
    path('goods/<int:pk>/', views.BaykeShopSPUView.as_view({'get': 'retrieve'}), name="spu-detail"),
    path('goods/', views.BaykeShopSPUView.as_view({'get': 'list'}), name="spu-list"),
    path('cart/', views.BaykeShopCartView.as_view({'get': 'list'}), name="cart-list"),
    
    path('order/', views.BaykeShopOrderView.as_view({'get':'list'}), name='order-list'),
    path('order/create/', views.BaykeShopOrderView.as_view({'post': 'create'}), name="order-create"),
    path('order/<int:pk>/confirm/', views.BaykeShopOrderView.as_view({'get': 'orderconfirm'}), name="order-confirm"),
    # 发起支付请求
    path('order/<int:pk>/pay/', views.BaykeShopOrderView.as_view({'patch': 'partial_update'}), name="order-pay"),
    path('order/<int:pk>/confirmok/', views.BaykeShopOrderView.as_view({'post': 'confirmok', 'get': 'confirmok'}), name="order-confirmok"),
    path('order/<int:pk>/comment/', views.BaykeShopOrderView.as_view({'get': 'ordercomment', 'post': 'ordercomment'}), name="order-comment"),
    # 余额支付
    path('order/<int:pk>/paybanlance', views.BaykeShopOrderView.as_view({'get': 'paybanlance'}), name="order-banlancepay"),


    path('menmber/', views.BaykeUserView.as_view(), name='menmber'),
    path('user/<int:pk>/patch/', views.BaykeUserUpdateView.as_view({'patch': 'partial_update'}), name='user-update'),
    path('balance/', views.BaykeUserUpdateView.as_view({'get': 'balance'}), name='balance'),
    
    path('address/', views.BaykeAddressView.as_view({'get': 'list'}), name='address'),
    # 支付宝支付后回调
    path('alipay/', views.AliPayCallBackView.as_view(), name='alipay'),
    # 余额充值后回调
    path('balance_recharge/', views.BalanceRechargeAliPayCallBackView.as_view(), name='balance_recharge'),
    
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.BaykeRegisterView.as_view(), name='register'),
]

baykeshop/urls.py
from django.urls import path, include
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('', include('baykeshop.apps.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('baykeshop.api.urls')),
    path('docs/', include_docs_urls(title='baykeShop API'))
]

baykesite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baykeshop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baykeshop/apps/badmin/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :models.py
@说明    :后台菜单管理
@时间    :2023/07/16 10:14:45
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission, Group
from django.utils.translation import gettext_lazy as _

from baykeshop.conf import bayke_settings
from baykeshop.common.models import BaseModelMixin
from baykeshop.common.validators import validate_phone


class BaykeSiteMenus(BaseModelMixin):
    """ 后台管理菜单自定义 """
    name = models.CharField(_("名称"), max_length=50, unique=True)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    icon = models.CharField(_("图标"), max_length=50, blank=True, default="")
    permission = models.OneToOneField(
        Permission, 
        on_delete=models.CASCADE, 
        blank=True, 
        null=True,
        verbose_name=_("权限")
    )

    # TODO: Define fields here

    class Meta:
        ordering = ['-add_date']
        verbose_name = 'SiteMenus'
        verbose_name_plural = 'SiteMenus'

    def __str__(self):
        return self.name


class BaykeFrontedMenus(BaseModelMixin):
    """ 前后端分离管理菜单 """
    name = models.CharField(_("名称"), max_length=50, unique=True)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    path = models.CharField("path", max_length=100, blank=True, default="")
    component = models.CharField("组件", max_length=50, blank=True, null=True)
    meta = models.JSONField(blank=True, null=True, verbose_name="meta")
    redirect = models.CharField(
        "跳转地址", 
        max_length=50, 
        blank=True, 
        default="", 
        help_text="格式应为`/home`"
    )
    sort = models.PositiveSmallIntegerField("排序", default=1)

    # TODO: Define fields here

    class Meta:
        ordering = ['sort']
        verbose_name = 'BaykeFrontedMenus'
        verbose_name_plural = 'BaykeFrontedMenus'

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.meta:
            self.meta = {
                "title": self.name,
                "hidden": False,
                "affix": False,
                "icon": "menu",
                "type": "menu", # menu，button，iframe, link
                "hiddenBreadcrumb": False,
                "active": False,
                "color": "black",
                "fullpage": False
            }
        super().save(*args, **kwargs)


class BaykePermissionAction(BaseModelMixin):
    """Model definition for BaykePermissionAction."""
    class RequestMethod(models.TextChoices):
        GET = "GET", _("查看")
        POST = "POST", _("新增")
        PUT = "PUT", _("修改")
        PATCH = "PATCH", _("局部修改")
        DELETE = "DELETE", _("删除")
    
    permission = models.OneToOneField(Permission, on_delete=models.CASCADE, verbose_name=_("权限"))
    menus = models.ForeignKey(BaykeFrontedMenus, on_delete=models.CASCADE, verbose_name=_("菜单"), blank=True, null=True)
    apiname = models.CharField(_("api接口name"), max_length=50, blank=True, default="", help_text="url的name别名，用来反解url")
    request_method = models.CharField(choices=RequestMethod.choices, max_length=10, blank=True, default="GET")
    mark = models.CharField(_("备注"), max_length=150, blank=True, default="")
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykePermissionAction."""
        ordering = ['-add_date']
        verbose_name = 'BaykePermissionAction'
        verbose_name_plural = 'BaykePermissionActions'

    def __str__(self):
        """Unicode representation of BaykePermissionAction."""
        return self.permission.codename


class BaykeDepartment(BaseModelMixin):
    """Model definition for department."""
    name = models.CharField("名称", max_length=50)
    parent = models.ForeignKey(
        "self", 
        on_delete=models.CASCADE, 
        blank=True, 
        null=True, 
        verbose_name="上级部门"
    )
    mark = models.CharField("备注", max_length=150, blank=True, default="")
    sort = models.PositiveSmallIntegerField("排序", default=1)
    is_enable = models.BooleanField("启用状态", default=True)

    # TODO: Define fields here

    class Meta:
        """Meta definition for department."""
        ordering = ["-sort", "-add_date"]
        verbose_name = 'department'
        verbose_name_plural = 'departments'
        constraints = [
            # 一个总公司下不能有相同的部门
            models.UniqueConstraint("name", "parent", name="dept_name_parent_unique")
        ]

    def __str__(self):
        """Unicode representation of department."""
        return self.name


class BaykeUser(BaseModelMixin):
    """Model definition for BaykeUser."""
    
    class UserType(models.TextChoices):
        FRONTED = "FRONTED", _("前台用户")
        SYSTEM = "SYSTEM", _("后台用户")
    
    owner = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, verbose_name=_("用户"))
    name = models.CharField(_("姓名"), max_length=50)
    dept = models.ForeignKey(BaykeDepartment, on_delete=models.SET_NULL, verbose_name="归属部门", blank=True, null=True)
    phone = models.CharField("手机号", blank=True, null=True, max_length=11, validators=[validate_phone])
    user_type = models.CharField(choices=UserType.choices, default=UserType.SYSTEM, max_length=50, verbose_name=_("用户类型"))
    sex = models.PositiveSmallIntegerField(choices=((0, "未知"), (1, "男"), (2, "女")), default=0, verbose_name=_("性别"))
    about = models.CharField(_("简介"), max_length=150, default="我喜欢baykeshop这个程序！", blank=True)
    avatar = models.ImageField(_("头像"), upload_to="avatar/", max_length=200, blank=True, null=True)
    balance = models.DecimalField(_("余额"), max_digits=8, decimal_places=2, blank=True, default=0)
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeUser."""
        ordering = ["-add_date"]
        verbose_name = 'BaykeUser'
        verbose_name_plural = 'BaykeUsers'

    def __str__(self):
        """Unicode representation of BaykeUser."""
        return self.name


class BaykeRoles(BaseModelMixin):
    """Model definition for BaykeRoles."""
    
    class PermRange(models.IntegerChoices):
        ALL = 1, _("全部可见")
        OWNER = 2, _("本人可见")
        DEPTS = 3, _("所在部门可见")
        DEPT = 4, _("所在部门及子级可见")
        SELECT = 5, _("选择的部门可见")
        CUSTOM = 6, _("自定义数据权限")
        
    group = models.OneToOneField(Group, on_delete=models.CASCADE, verbose_name=_("权限组"))
    codename = models.CharField(_("角色标识"), max_length=50, unique=True)
    depts = models.ManyToManyField(BaykeDepartment, blank=True, verbose_name="数据权限-关联部门")
    menus = models.ManyToManyField(BaykeFrontedMenus, blank=True, verbose_name=_("菜单"))
    perm_range = models.IntegerField(choices=PermRange.choices, default=PermRange.ALL, verbose_name=_("权限范围"))
    dashboard_grid = models.JSONField(blank=True, default=list, verbose_name=_("控制台模块权限"), help_text="当dashboard值为0时才有用！")
    dashboard = models.PositiveSmallIntegerField(default=0, blank=True, verbose_name=_("控制台视图"))
    sort = models.IntegerField(default=0, verbose_name=_("排序"))
    status = models.BooleanField(default=True, verbose_name=_("状态"))
    remark = models.CharField(_("备注"), max_length=150, blank=True, default="")

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeRoles."""
        ordering = ["-sort"]
        verbose_name = 'BaykeRoles'
        verbose_name_plural = 'BaykeRoless'

    def __str__(self):
        """Unicode representation of BaykeRoles."""
        return self.codename


class BaykeDictKey(BaseModelMixin):
    """ 字典分类 """
    name = models.CharField(_("名称"), max_length=50)
    code = models.SlugField(_("字典名称"), max_length=50, unique=True)
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, blank=True, null=True, verbose_name=_("父级")
    )
    status = models.BooleanField(default=True, verbose_name=_("状态"))
    sort = models.PositiveIntegerField(default=1, verbose_name=_("排序"))
    
    # TODO: Define fields here

    class Meta:
        ordering = ['-sort']
        verbose_name = 'ByakeDictKey'
        verbose_name_plural = 'ByakeDictKeys'

    def __str__(self):
        return self.name
    
    
class BaykeDictValue(models.Model):
    """Model definition for BaykeDictValue."""
    name = models.CharField(_("名称"), max_length=50)
    key = models.CharField(_("值"), max_length=150)
    dic = models.ForeignKey(BaykeDictKey, on_delete=models.CASCADE, verbose_name=_("字典key"))
    status = models.BooleanField(default=True, verbose_name=_("状态"))
    sort = models.PositiveIntegerField(default=1, verbose_name=_("排序"))
    
    # TODO: Define fields here

    class Meta:
        ordering = ['-sort']
        verbose_name = 'BaykeDictValue'
        verbose_name_plural = 'BaykeDictValue'

    def __str__(self):
        return self.name


class BaykeImage(BaseModelMixin):
    """Model definition for BaykeImage."""
    img = models.ImageField(_("图片"), upload_to="upload/", max_length=200)
    sort = models.PositiveSmallIntegerField(default=1, verbose_name=_("排序"))
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeImage."""
        ordering = ['-sort']
        verbose_name = 'BaykeImage'
        verbose_name_plural = 'BaykeImages'

    def __str__(self):
        """Unicode representation of BaykeImage."""
        return self.img.name


class BaykeSystem(BaseModelMixin):
    """Model definition for BaykeSystem."""
    site_title = models.CharField(_("站点名称"), max_length=50, default="baykeshop商城系统")
    logo_url = models.URLField(_("logo地址"), max_length=200, blank=True, default="")
    extend_json = models.JSONField(_("扩展配置"), default=dict, blank=True, null=True)
    copyright = models.CharField(_("版权信息"), max_length=150, blank=True, default="baykeshop版权所有")

    # TODO: Define fields here

    class Meta:

baykeshop/models/statis.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :statis.py
@说明    :站点统计相关
@时间    :2023/04/21 12:48:30
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

baykeshop/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :forms.py
@说明    :表单
@时间    :2023/05/01 21:20:28
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.flatpages.forms import FlatpageForm as BaseFlatpageForm

from baykeshop.tinymce import Tinymce
from baykeshop.conf import bayke_settings


class SearchForm(forms.Form):
    
    search = forms.CharField(
        max_length=32, 
        label="搜索", 
        widget=forms.TextInput(
            {
                'type': 'search', 
                'class': 'input',
                'placeholder': f'{bayke_settings.SEARCH_VALUE}'
            }
        ))


class LoginForm(AuthenticationForm):
    """ 登录表单 """
    username = UsernameField(
        widget=forms.TextInput(attrs={
            "autofocus": True, 
            "class": "input", 
            "placeholder":" 请输入用户名..."
        }))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password", 
            "class": "input", 
            "placeholder":" 请输入密码..."
        }),
    )
    

class FlatpageForm(BaseFlatpageForm):
    
    class Meta(BaseFlatpageForm.Meta):
        widgets = {
            'content': Tinymce(),
        }

baykeshop/apps/shop/templates/baykeshop/comp/action.html
<div id="orderaAction{{ order.id }}">
    <p class=" has-text-weight-bold pt-1 pb-1 has-text-right">共{{ payorder.count }}件商品，总金额{{ payorder.total_amount }}元（含运费）</p>
    <div class=" buttons is-justify-content-end">
    {% if order.status == 1 %}
        <a class="button is-primary is-small" href="{% url 'shop:order-confirm' order.id %}">立即支付</a>
    {% elif order.status == 3 %}
        <button class="button is-primary is-small" @click="confirmProduct">确认收货</button>
    {% elif order.status == 4 and not payorder.is_commented %}
        <a class=" button is-primary is-small" href="{% url 'shop:order-comment' order.id %}">立即评价</a>
    {% endif %}
    <a href="{% url 'shop:order-confirmok' order.id %}" class="button is-small">订单详情</a>
    </div>
</div>

<script>
    var confirmAction = new Vue({
        el: '#orderaAction{{ order.id }}',
        delimiters: ['{$', '$}'],
        methods: {
            confirmProduct(){
                request({
                    url:'{% url "shop:order-confirmok" order.id %}',
                    method: 'post'
                }).then(res => {
                    setTimeout(function(){location.reload()}, 1000)
                })
            }
        }
    })
</script>

baykeshop/apps/shop/templates/baykeshop/comp/banners.html
<div id="carousel" class="container">
    <template>
        <b-carousel>
            <b-carousel-item v-for="(carousel, i) in carousels" :key="i">
                <section :class="`hero is-medium`">
                    <a class="image" :href="carousel.target">
                        <img width="100%" :src="`${carousel.img}`" :alt="carousel.desc"> 
                    </a>
                </section>
            </b-carousel-item>
        </b-carousel>
    </template>
</div>
<script>
    var carousel = new Vue({
        el: '#carousel',
        delimiters: ['{$', '$}'],
        created() {
            this.getBanners()
        },
        data: {
            carousels: []
        },
        methods: {
            getBanners(){
                fetch("{% url 'shop_api:banner-list' %}").then(
                    res => res.json()
                ).then(data => {
                    this.carousels = data.results
                })
            }
            
        },
    })
</script>

baykeshop/apps/shop/templates/baykeshop/comp/head_top.html
{% load shoptags %}
<div id="header-top" class="has-background-black-bis">
    <div class="is-flex is-justify-content-space-between is-align-items-center container" style="height:40px">
        <div class="head-top-left">
            {% block head_top_left %}
            欢迎您光临本店！
            {% endblock %}  
        </div>
        <div class="head-top-right">
            {% block head_top_right %}
            {% if request.user.is_authenticated %}
            <div class="dropdown is-hoverable usertools">
                <div class="dropdown-trigger">
                  <button class="button is-radiusless is-shadowless" aria-haspopup="true" aria-controls="dropdown-menu4" 
                    style="background: none; border:none">
                    <span>欢迎您，{{ request.user.username }}</span>
                    <span class="icon is-small">
                      <i class="mdi mdi-menu-down" aria-hidden="true"></i>
                    </span>
                  </button>
                </div>
                <div class="dropdown-menu" id="dropdown-menu4" role="menu" style="z-index:1000">
                  <div class="dropdown-content">
                    <a class="dropdown-item" href="{% url 'shop:menmber' %}">
                        <span class="mdi mdi-account-box-outline"></span>
                        个人中心
                    </a>
                    <a class="dropdown-item" href="{% url 'shop:order-list' %}">
                        <span class="mdi mdi-basket-plus-outline"></span>
                        我的订单
                    </a>
                    <div class=" dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'shop:logout' %}">
                        <span class="mdi mdi-logout"></span>
                        退出
                    </a>
                  </div>
                </div>
            </div>
            {% else %}
            <a class="mr-2" href="{% url 'shop:login' %}" target="_top">
                <span class="icon"><i class="mdi mdi-login"></i></span>
                登录
            </a> <span class="is-size-6">|</span>
            <a class="mr-3" href="{% url 'shop:register' %}" target="_top">
                <span class="icon"><i class="mdi mdi-cash-register"></i></span>
                注册
            </a>
            {% endif %}
            {% cartscount request as cartcount %}
            <a class="cart" href="{% url 'shop:cart-list' %}" id="cart">
                <span class="icon"><i class="mdi mdi-cart-check"></i></span>
                购物车({$ cartcount $})
            </a>
            {% endblock %}
        </div>
    </div>
</div>
<script>
    var bayke = new Vue({
        el: '#cart',
        delimiters: ['{$', '$}'],
        data: {
           cartcount: Number('{% cartscount request %}')
        },
        methods: {
            toastMessage(type, message){
                return this.$buefy.toast.open({
                    message: message,
                    type: type
                })
            },
        },
    })
</script>

baykeshop/apps/shop/templates/baykeshop/comp/navbar.html
<div id="navbar">
    <template>
        <b-navbar spaced shadow transparent wrapper-class="{% block navclass %}container{% endblock %}">
            <template #brand>
                <b-navbar-item tag="div">
                    {% block navbar_logo %}
                    <h1 class="is-size-4 has-text-weight-medium">baykeShop</h1>
                    {% endblock %} 
                </b-navbar-item>
            </template>
            <template #start>
                {% block navbar_start %}
                <b-navbar-item href="{% url 'shop:home' %}">
                    首页
                </b-navbar-item>
                <b-navbar-item href="{% url 'shop:spu-list' %}">
                    全部分类
                </b-navbar-item>
                <!-- <b-navbar-item href="">
                    商城资讯
                </b-navbar-item> -->
                {% for cate in navs %}
                <b-navbar-dropdown label="{{ cate.name }}">
                    {% for sub_cate in cate.children %}
                    <b-navbar-item href="{% url 'shop:spu-list' %}?category={{ sub_cate.id }}">
                        {{ sub_cate.name }}
                    </b-navbar-item>
                    {% endfor %}
                </b-navbar-dropdown>
                {% endfor %}
                {% endblock %}             
            </template>
    
            <template #end>
                {% block navbar_end %}
                <b-navbar-item tag="div">
                    <form action="/goods/" method="get">
                        <div class="field-body">
                          <div class="field is-expanded">
                            <div class="field has-addons">
                              <p class="control is-expanded has-icons-left">
                                <input class="input" type="search" name="search" id="id_search" value="{{ words }}" placeholder="请输入商品关键词搜索" maxlength="32">
                                <span class="icon is-left">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                              </p>
                              <p class="control has-icons-right">
                                <input class="button is-primary" type="submit" value="搜索">
                              </p>
                            </div>
                          </div>
                        </div>
                    </form>
                </b-navbar-item>
                {% endblock %} 
            </template>
        </b-navbar>
    </template>
</div>

<script>
    var navbar = new Vue({
        el: '#navbar',
        delimiters: ['{$', '$}']
    })
</script>

baykeshop/apps/shop/templates/baykeshop/comp/spubox.html
<figure class="image is-1by1">
    <a href="{% url 'shop:spu-detail' spu.id %}"><img src="{{ spu.img }}" alt="{{ spu.title }}"></a>
</figure>
<div class="is-flex-grow-1 is-flex is-flex-direction-column is-justify-content-center">
    <p class="has-text-justified spu-title pl-3 pr-3">
        <a href="" class="has-text-black-ter">{{ spu.title|truncatechars:40 }}...</a>
    </p> 
</div>
<div class="pl-2 pr-2 pb-2">
    <div class="is-flex is-align-items-center is-justify-content-space-between">
        <span class="is-size-5 has-text-danger-dark">¥{{ spu.price }}</span>
        <span class="tag is-danger is-light is-size-7">券</span>
    </div>
    <div class="is-flex is-align-items-center is-justify-content-space-between">
        <span class="is-size-7 has-text-grey-light">{{ spu.sales }}人付款</span>
        <span class="is-size-7 has-text-grey-light">{{ spu.comment_choices__avg }}分</span>
    </div>
</div>