bayke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baykeshop.urls')),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

baykeshop/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('shop/', include(('baykeshop.api.shop.urls', 'baykeshop'), namespace="shop_api")),
    path('auth/', include(('baykeshop.api.auth.urls', 'baykeshop'), namespace='auth_api')),
    path('badmin/', include(('baykeshop.api.badmin.urls', 'baykeshop'), namespace='badmin_api')),
    path('comment/', include(('baykeshop.api.comment.urls', 'baykeshop'), namespace='comment_api')),
]

baykeshop/apps/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name="home"),
    path('goods/<int:pk>/', views.BaykeShopSPUView.as_view({'get': 'retrieve'}), name="spu-detail"),
    path('goods/', views.BaykeShopSPUView.as_view({'get': 'list'}), name="spu-list"),
    path('cart/', views.BaykeShopCartView.as_view({'get': 'list'}), name="cart-list"),
    
    path('order/', views.BaykeShopOrderView.as_view({'get':'list'}), name='order-list'),
    path('order/create/', views.BaykeShopOrderView.as_view({'post': 'create'}), name="order-create"),
    path('order/<int:pk>/confirm/', views.BaykeShopOrderView.as_view({'get': 'orderconfirm'}), name="order-confirm"),
    # 发起支付请求
    path('order/<int:pk>/pay/', views.BaykeShopOrderView.as_view({'patch': 'partial_update'}), name="order-pay"),
    path('order/<int:pk>/confirmok/', views.BaykeShopOrderView.as_view({'post': 'confirmok', 'get': 'confirmok'}), name="order-confirmok"),
    path('order/<int:pk>/comment/', views.BaykeShopOrderView.as_view({'get': 'ordercomment', 'post': 'ordercomment'}), name="order-comment"),
    # 余额支付
    path('order/<int:pk>/paybanlance', views.BaykeShopOrderView.as_view({'get': 'paybanlance'}), name="order-banlancepay"),


    path('menmber/', views.BaykeUserView.as_view(), name='menmber'),
    path('user/<int:pk>/patch/', views.BaykeUserUpdateView.as_view({'patch': 'partial_update'}), name='user-update'),
    path('balance/', views.BaykeUserUpdateView.as_view({'get': 'balance'}), name='balance'),
    
    path('address/', views.BaykeAddressView.as_view({'get': 'list'}), name='address'),
    # 支付宝支付后回调
    path('alipay/', views.AliPayCallBackView.as_view(), name='alipay'),
    # 余额充值后回调
    path('balance_recharge/', views.BalanceRechargeAliPayCallBackView.as_view(), name='balance_recharge'),
    
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.BaykeRegisterView.as_view(), name='register'),
]

baykeshop/urls.py
from django.urls import path, include
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('', include('baykeshop.apps.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('baykeshop.api.urls')),
    path('docs/', include_docs_urls(title='baykeShop API'))
]

baykesite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baykeshop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baykeshop/apps/comment/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
# Create your models here.
from baykeshop.common.models import ContentTypeAbstract


class BaykeShopComment(ContentTypeAbstract):
    """ 模型的通用关系 """
    
    class CommentChoices(models.IntegerChoices):
        GOOD = 5, _('好评')
        SO = 3, _('中评')
        BAD = 1, _('差评')
        
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="用户")
    content = models.CharField("留言内容", max_length=200)
    reply = models.CharField("回复内容", max_length=200, blank=True, default="")
    comment_choices = models.PositiveSmallIntegerField(
        default=5,
        choices=CommentChoices.choices,
        verbose_name="评分"
    )

    class Meta:
        ordering = ['-add_date']
        verbose_name = 'BaykeShopComment'
        verbose_name_plural = 'BaykeShopComment'
        
    def __str__(self):
        return self.content

baykeshop/apps/shop/models/cart.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from baykeshop.common.models import BaseModelMixin
from .goods import BaykeShopSKU


class BaykeShopCart(BaseModelMixin):
    """Model definition for BaykeShopCart."""
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("用户"))
    sku = models.ForeignKey(BaykeShopSKU, on_delete=models.CASCADE, verbose_name=_("规格"))
    num = models.PositiveSmallIntegerField(default=1, verbose_name=_("数量"))
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeShopCart."""
        ordering = ['-add_date']
        verbose_name = 'BaykeShopCart'
        verbose_name_plural = 'BaykeShopCarts'
        constraints = [
            models.UniqueConstraint('owner', 'sku', name='unique_owner_sku'),
        ]

    def __str__(self):
        """Unicode representation of BaykeShopCart."""
        return self.sku.spu.title

    @classmethod
    def get_cart_count(cls, user) -> dict: 
        # 当前用户的购物车商品数量
        from django.db.models import Sum
        counts = cls.objects.filter(owner=user).aggregate(Sum('num'))
        return counts.get('num__sum') if counts.get('num__sum') else 0

baykeshop/apps/shop/models/goods.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from baykeshop.common.models import BaseModelMixin
from baykeshop.common.validators import validate_count

class BaykeShopCategory(BaseModelMixin):
    """Model definition for BaykeShopCategory."""
    name = models.CharField(_("名称"), max_length=50)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    icon = models.ImageField(_("分类图标"), upload_to="shop/category", max_length=200, blank=True, null=True)
    sort = models.PositiveSmallIntegerField(_("排序"), default=1)
    status = models.BooleanField(_("状态"), default=True)

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeShopCategory."""
        ordering = ['-sort']
        verbose_name = 'BaykeShopCategory'
        verbose_name_plural = 'BaykeShopCategorys'

    def __str__(self):
        """Unicode representation of BaykeShopCategory."""
        return self.name


class BaykeshopBrand(BaseModelMixin):
    """Model definition for BaykeshopBrand."""
    name = models.CharField(_("品牌名称"), max_length=50)
    logo = models.ImageField(
        _("品牌logo"), upload_to="shop/brand/", max_length=200, blank=True, null=True)
    sort = models.PositiveSmallIntegerField(_("排序"), default=1)
    status = models.BooleanField(_("状态"), default=True)
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeshopBrand."""
        ordering = ['-sort']
        verbose_name = 'BaykeshopBrand'
        verbose_name_plural = 'BaykeshopBrands'

    def __str__(self):
        """Unicode representation of BaykeshopBrand."""
        return self.name


class BaykeShopSPU(BaseModelMixin):
    """Model definition for BaykeShopSPU."""
    title = models.CharField(_("标题"), max_length=80)
    subtitle = models.CharField(_("副标题"), max_length=150, blank=True, default="")
    keywords = models.CharField(_("商品关键字"), max_length=150, blank=True, default="")
    desc = models.CharField(_("商品简介"), max_length=150, blank=True, default="")
    content = models.TextField(_("详情"))
    unit = models.CharField(_("单位"), max_length=50)
    images = models.JSONField(_("轮播图"), default=list, validators=[validate_count], blank=True)
    category = models.ManyToManyField(BaykeShopCategory, blank=True, verbose_name=_("分类"))
    brand = models.ForeignKey(BaykeshopBrand, on_delete=models.SET_NULL, blank=True, null=True, verbose_name=_("品牌"))
    skutype = models.PositiveSmallIntegerField(choices=((0, "单规格"), (1, "多规格")), default=0, blank=True, verbose_name="规格类型")
    freighttype = models.PositiveSmallIntegerField(choices=((0, "固定运费"), (1, "运费模板")), default=0, blank=True, verbose_name="运费类型")
    expresstype = models.PositiveSmallIntegerField(choices=((0, "快递"), (1, "上门自提")), default=0, blank=True, verbose_name="运费类型")
    freight = models.DecimalField(_("运费"), max_digits=8, decimal_places=2, blank=True, default=0)
    sort = models.IntegerField(default=1, verbose_name=_("排序"))
    status = models.BooleanField(default=True, verbose_name=_("商品状态(上下架)"))

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeShopSPU."""
        ordering = ['-sort', '-add_date']
        verbose_name = 'BaykeShopSPU'
        verbose_name_plural = 'BaykeShopSPUs'

    def __str__(self):
        """Unicode representation of BaykeShopSPU."""
        return self.title

class BaykeShopSpec(BaseModelMixin):
    """Model definition for BaykeShopSpec."""
    name = models.CharField(_("名称"), max_length=50)
    sort = models.IntegerField(default=1, verbose_name=_("排序"))
    status = models.BooleanField(default=True, verbose_name=_("状态"))
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeShopSpec."""
        ordering = ['-add_date']
        verbose_name = 'BaykeShopSpec'
        verbose_name_plural = 'BaykeShopSpecs'

    def __str__(self):
        """Unicode representation of BaykeShopSpec."""
        return self.name


class BaykeShopSpecValue(BaseModelMixin):
    """Model definition for BaykeShopSpecValue."""
    value = models.CharField(_("规格值"), max_length=50)
    spec = models.ForeignKey(BaykeShopSpec, on_delete=models.CASCADE, verbose_name=_("规格"))
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeShopSpecValue."""
        ordering = ['-add_date']
        verbose_name = 'BaykeShopSpecValue'
        verbose_name_plural = 'BaykeShopSpecValues'

    def __str__(self):
        """Unicode representation of BaykeShopSpecValue."""
        return self.value


class BaykeShopSKU(BaseModelMixin):
    """Model definition for BaykeShopSKU."""

    stock = models.PositiveSmallIntegerField(_("库存"), default=0)
    sales = models.PositiveIntegerField(_("销量"), default=0)
    # img = models.ImageField(_("主图"), upload_to="shop/sku/",
    #                         max_length=200, blank=True, null=True)
    img = models.CharField(_("主图"), max_length=200, blank=True, default="")
    spu = models.ForeignKey(
        BaykeShopSPU, on_delete=models.CASCADE, verbose_name=_("商品"))
    spec_values = models.ManyToManyField(
        BaykeShopSpecValue, blank=True, verbose_name=_("规格"))
    price = models.DecimalField(_("售价"), max_digits=8, decimal_places=2, blank=True, default=0.00)
    cost_price = models.DecimalField(_("成本价"), max_digits=8, decimal_places=2, blank=True, default=0.00)
    retail_price = models.DecimalField(
        _("零售价"), max_digits=10, decimal_places=2, blank=True, default=0.00)
    item = models.CharField(_("商品编号"), max_length=50, blank=True)
    weight = models.FloatField(_("重量"), blank=True, default=0)
    vol = models.FloatField(_("体积"), blank=True, default=0)
    status = models.BooleanField(default=True, verbose_name=_("商品状态(上下架)"))

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeShopSKU."""
        ordering = ['-add_date']
        verbose_name = 'BaykeShopSKU'
        verbose_name_plural = 'BaykeShopSKUs'

    def __str__(self):
        """Unicode representation of BaykeShopSKU."""
        return self.spu.title


class BaykeShopBanner(BaseModelMixin):
    """Model definition for BaykeShopBanner."""
    img = models.ImageField(upload_to='banner', max_length=100)
    desc = models.CharField(_("描述"), max_length=150, blank=True, default="")
    target = models.URLField(_("跳转链接"), max_length=200, blank=True, null=True)
    sort = models.PositiveSmallIntegerField(default=1)
    status = models.BooleanField(default=True)
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeShopBanner."""
        ordering = ['sort', '-add_date']
        verbose_name = 'BaykeShopBanner'
        verbose_name_plural = 'BaykeShopBanners'

    def __str__(self):
        """Unicode representation of BaykeShopBanner."""
        return self.desc

baykeshop/apps/shop/models/user.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from baykeshop.common.models import BaseModelMixin


class BaykeUserBalanceLog(BaseModelMixin):
    """ 用户余额变动表 """
    
    class BalanceChangeStatus(models.IntegerChoices):
        # 收支状态
        ADD = 1, _('增加')
        MINUS = 2, _('支出')
    
    class BalanceChangeWay(models.IntegerChoices):
        # 收支渠道或方式
        PAY = 1, _('线上充值')        
        ADMIN = 2, _('管理员手动更改') 
        SHOP = 3, _('余额抵扣商品')
    
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="用户")
    amount = models.DecimalField("金额", max_digits=15, decimal_places=2)
    change_status = models.PositiveSmallIntegerField(
        choices=BalanceChangeStatus.choices, 
        blank=True,
        null=True
    )
    change_way = models.PositiveSmallIntegerField(
        choices=BalanceChangeWay.choices, 
        default=BalanceChangeWay.ADMIN        # 默认为后台
    )

    class Meta:
        verbose_name = '余额明细'
        verbose_name_plural = verbose_name

    def __str__(self):
        return f"{self.owner.username}-{self.amount}"
    
    @classmethod
    def balance_queryset(cls, user):
        return cls.objects.filter(owner=user)
    
    @classmethod
    def add_sum_amount(cls, user):
        # 累计充值
        amount__sum = cls.balance_queryset(user).filter(change_status=1).aggregate(Sum('amount')).get('amount__sum')
        return amount__sum if amount__sum else 0
    
    @classmethod
    def minus_sum_amount(cls, user):
        # 累计消费
        amount__sum = cls.balance_queryset(user).filter(change_status=2).aggregate(Sum('amount')).get('amount__sum')
        return amount__sum if amount__sum else 0
    

class BaykeAddress(BaseModelMixin):
    """ 收货地址 """
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="用户")
    name = models.CharField("签收人", max_length=50)
    phone = models.CharField("手机号", max_length=11)
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    province = models.CharField(max_length=150, verbose_name="省")
    city = models.CharField(max_length=150, verbose_name="市")
    county = models.CharField(max_length=150, verbose_name="区/县")
    address = models.CharField(max_length=150, verbose_name="详细地址")
    is_default = models.BooleanField(default=False, verbose_name="设为默认")
    
    class Meta:
        verbose_name = "收货地址"
        verbose_name_plural = verbose_name
       
    def __str__(self):
        return f'{self.name} {self.address}'

baykeshop/models/statis.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :statis.py
@说明    :站点统计相关
@时间    :2023/04/21 12:48:30
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

baykeshop/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :forms.py
@说明    :表单
@时间    :2023/05/01 21:20:28
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.flatpages.forms import FlatpageForm as BaseFlatpageForm

from baykeshop.tinymce import Tinymce
from baykeshop.conf import bayke_settings


class SearchForm(forms.Form):
    
    search = forms.CharField(
        max_length=32, 
        label="搜索", 
        widget=forms.TextInput(
            {
                'type': 'search', 
                'class': 'input',
                'placeholder': f'{bayke_settings.SEARCH_VALUE}'
            }
        ))


class LoginForm(AuthenticationForm):
    """ 登录表单 """
    username = UsernameField(
        widget=forms.TextInput(attrs={
            "autofocus": True, 
            "class": "input", 
            "placeholder":" 请输入用户名..."
        }))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password", 
            "class": "input", 
            "placeholder":" 请输入密码..."
        }),
    )
    

class FlatpageForm(BaseFlatpageForm):
    
    class Meta(BaseFlatpageForm.Meta):
        widgets = {
            'content': Tinymce(),
        }

baykeshop/apps/shop/templates/baykeshop/goods/cates.html
{% load shoptags %}
{{ request.query_params.category|json_script:"cateData" }}
<div id="filterCates" class="mb-3">
    {% filtercates request as category %}
    <div class="box is-marginless is-radiusless">
        <a href="{% url 'shop:spu-list' %}" class="mr-2 {% if request.path == '/goods/' and not category.cate %} has-text-danger-dark {% else %} has-text-black {% endif %}">
            全部分类
        </a>
        {% for item in category.cates %}
            <a class="mr-2 {% if item.id == category.cate.id or item.id == category.cate.parent.id %} has-text-danger-dark {% else %} has-text-black {% endif %}" 
            href="?category={{ item.id }}&ordering={{ request.query_params.ordering }}">{{ item.name }}</a>
        {% endfor %}
    </div>
    <div class="box is-radiusless">
        <div>
            <span class=" has-text-grey-light">分类：</span>
            {% for item in category.sub_cates %}
                <a class="mr-2 {% if item.id == category.cate.id %} has-text-danger-dark {% else %} has-text-black {% endif %}" 
                    href="?category={{ item.id }}&ordering={{ request.query_params.ordering }}">{{ item.name }}</a>
            {% endfor %}
        </div>
        <div class="mt-2">
            <span class=" has-text-grey-light">排序：</span>
            
            {% if request.GET.ordering == '-baykeshopsku__price' %}
            <a class="mr-2 has-text-black {% if request.GET.ordering == '-baykeshopsku__price' or request.GET.ordering == 'baykeshopsku__price' %} has-text-danger-dark {% endif %}" href="?ordering=baykeshopsku__price&category={{ request.query_params.category }}">价格
                {% if request.GET.ordering == '-baykeshopsku__price' %}<span class="mdi mdi-arrow-down"></span>{% endif %}
            </a>
            {% else %}
            <a class="mr-2 has-text-black {% if request.GET.ordering == '-baykeshopsku__price' or request.GET.ordering == 'baykeshopsku__price' %} has-text-danger-dark {% endif %}" href="?ordering=-baykeshopsku__price&category={{ request.query_params.category }}">价格
                {% if request.GET.ordering == 'baykeshopsku__price' %}<span class="mdi mdi-arrow-up"></span>{% endif %}
            </a>
            {% endif %}
    
            {% if request.GET.ordering == '-baykeshopsku__sales' %}
            <a class="mr-2 has-text-black {% if request.GET.ordering == '-baykeshopsku__sales' or request.GET.ordering == 'baykeshopsku__sales' %} has-text-danger-dark {% endif %}" href="?ordering=baykeshopsku__sales&category={{ request.query_params.category }}">销量
                {% if request.GET.ordering == '-baykeshopsku__sales' %}<span class="mdi mdi-arrow-down"></span>{% endif %}
            </a>
            {% else %}
            <a class="mr-2 has-text-black {% if request.GET.ordering == '-baykeshopsku__sales' or request.GET.ordering == 'baykeshopsku__sales' %} has-text-danger-dark {% endif %}" href="?ordering=-baykeshopsku__sales&category={{ request.query_params.category }}">销量
                {% if request.GET.ordering == 'baykeshopsku__sales' %}<span class="mdi mdi-arrow-up"></span>{% endif %}
            </a>
            {% endif %}
    
            {% if request.GET.ordering == '-add_date' %}
            <a class="mr-2 has-text-black {% if request.GET.ordering == '-add_date' or request.GET.ordering == 'add_date' %} has-text-danger-dark {% endif %}" href="?ordering=add_date&category={{ request.query_params.category }}">上架时间
                {% if request.GET.ordering == '-add_date' %}<span class="mdi mdi-arrow-down"></span>{% endif %}
            </a>
            {% else %}
            <a class="mr-2 has-text-black {% if request.GET.ordering == '-add_date' or request.GET.ordering == 'add_date' %} has-text-danger-dark {% endif %}" href="?ordering=-add_date&category={{ request.query_params.category }}">上架时间
                {% if request.GET.ordering == 'add_date' %}<span class="mdi mdi-arrow-up"></span>{% endif %}
            </a>
            {% endif %}
        </div>
    </div>
</div>

<script>
    const cateData = JSON.parse(document.querySelector("#cateData").textContent)

    var filterCates = new Vue({
        el: "#filterCates",
        delimiters: ['{$', '$}'],
        data: {},
        created(){},
        methods: {}
    })

</script>

baykeshop/apps/shop/templates/baykeshop/goods/detail.html
{% extends 'baykeshop/base_site.html' %}

{% load shoptags %}

{% block title %}{{ title }}{% endblock %}
{% block meta_desc %}{{ desc }}{% endblock %}
{% block meta_kw %}{{ keywords }}{% endblock %}

{% block breadcrumb %}
<div class="container">
	<nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'shop:home' %}">首页</a></li>
            {% breadcrumbcate category as cates %}
            {% for cate in cates %}
            <li>
                <a href="">{{ cate.name }}</a>
            </li>
            {% endfor %}
			<li class="is-active"><a href="#" aria-current="page">{{ title }}</a></li>
		</ul>
	</nav>
</div>
{% endblock %}

{% block container %}
<div class="columns">
    <div class="column is-3">
        {% include 'baykeshop/goods/banners.html' with banners=images %}
    </div>
    <div class="column">
        <h1 class="title is-size-4">{{ title }}</h1>
        <p class="subtitle has-text-grey-dark">{{ subtitle }}</p>
        {% if skutype %}
            <!-- 多规格 -->
            {% include 'baykeshop/goods/multipleSpec.html' %}
        {% else %}
            <!-- 单规格 -->
            {% include 'baykeshop/goods/singleSpec.html' %}
        {% endif %}

        <!-- 加入购物车按钮及一键购买 -->
        <div class="box is-radiusless" id="payButton">
            <b-button 
                type="is-primary"
                @click="addCart"
                :disabled="stock ? false : true">
                加入购物车
            </b-button>
            <b-button 
                type="is-primary" 
                :disabled="stock ? false : true"
                @click="nowBuy"
                outlined>
                立即购买
            </b-button>
        </div>
        <!-- 加入购物车按钮及一键购买 -->
        <div class="box is-radiusless mt-3" id="goodsContent">
            <b-tabs class="block">
                <b-tab-item label="商品详情">
                    <div class="content">
                        {{ content|safe }}
                    </div>
                </b-tab-item>
                {% comments baykeshopsku_set as spucomments %}
                <b-tab-item label="商品评价">
                    <div class="is-flex is-justify-content-space-between p-2">
                        <div class="">满意度：{{ spucomments.rate }}%</div>
                        <div class="is-flex is-align-items-center">
                            <span> 评分：</span>
                            <b-rate 
                                :value="{{ spucomments.comment_choices__avg }}" 
                                disabled 
                                custom-text="{{ spucomments.comment_choices__avg }}分">
                            </b-rate>
                        </div>
                    </div>
                    <div class=" dropdown-divider"></div>
                    
                    {% for comment in spucomments.comments %}
                    <article class="media">
                        <figure class="media-left">
                            <p class="image is-32x32">
                                <img class="is-rounded" src="{% if comment.owner.baykeuser.avatar %}{{ comment.owner.baykeuser.avatar.url }}{% endif %}">
                            </p>
                        </figure>
                        <div class="media-content">
                            <p>
                                {{ comment.owner.username }}
                                <b-rate size="is-small" :value="{{ comment.comment_choices }}" disabled custom-text="{{ comment.comment_choices }}分"></b-rate>
                            </p>
                            <p class=" is-size-7">{{ comment.add_date }}</p>
                            <p class=" has-text-grey-light">{{ comment.content }}</p>
                            
                            {% if comment.reply %}
                            <div class="box is-shadowless has-background-light">
                                <span class="has-text-danger-dark">商家回复：</span> {{ comment.reply }}
                            </div>
                            {% endif %}
                        </div>
                        
                    </article>
                    {% endfor %}
                </b-tab-item>
            </b-tabs>
        </div>
    </div>
</div>
{% endblock %}


{% block vue %}
    <script>
        var payButton = new Vue({
            el: "#payButton",
            delimiters: ['{$', '$}'],
            data: {
                skutype: Number('{{ skutype }}')
            },
            computed: {
                stock(){
                    return this.skutype ? multipleSpec._data.stock : singleSpec._data.sku.stock
                },
                sku(){
                    return this.skutype ? multipleSpec._data.sku : singleSpec._data.sku
                },
                num(){
                    return this.skutype ? multipleSpec._data.num : singleSpec._data.num
                }
            },
            methods: {
                // 加入购物车
                addCart(){
                    request({
                        url: "{% url 'shop_api:cart-list' %}",
                        method: 'post',
                        data:{
                            sku: this.sku.id,
                            num: this.num
                        }
                    }).then(res => {
                        if (res.status == 403){
                            bayke.toastMessage("is-danger", "未登录，请登录后操作！")
                            return
                        }
                        if (res.status == 201) {
                            bayke._data.cartcount += this.num
                            bayke.toastMessage('is-success', '加入购物车成功')
                        }
                    })

                },
                // 立即购买
                nowBuy(){
                    request({
                        url: '{% url "shop:order-create" %}',
                        method: 'post',
                        data: {
                            baykeshopordersku_set: [
                                {
                                    sku: this.sku.id,
                                    count: this.num
                                }
                            ],
                            total_price: 0
                        }
                    }).then(res => {
                        if (res.status == 201){
                            location.replace(`/order/${res.data.id}/confirm/`)
                        }else if (res.status == 403){
                            bayke.toastMessage('is-danger', '未登录，请登录后操作！')
                        }else{
                            bayke.toastMessage('is-danger', '操作失败！')
                        }
                    })
                }
            },
        })


        var goodsContent = new Vue({
            el: "#goodsContent",
            delimiters: ['{$', '$}'],
            data: {},
        })

    </script>
{% endblock %}
    