bayke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baykeshop.urls')),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

baykeshop/api/urls.py
from django.urls import path, include

urlpatterns = [
    path('shop/', include(('baykeshop.api.shop.urls', 'baykeshop'), namespace="shop_api")),
    path('auth/', include(('baykeshop.api.auth.urls', 'baykeshop'), namespace='auth_api')),
    path('badmin/', include(('baykeshop.api.badmin.urls', 'baykeshop'), namespace='badmin_api')),
    path('comment/', include(('baykeshop.api.comment.urls', 'baykeshop'), namespace='comment_api')),
]

baykeshop/urls.py
from django.urls import path, include
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('', include('baykeshop.apps.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('baykeshop.api.urls')),
    path('docs/', include_docs_urls(title='baykeShop API'))
]

baykesite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baykeshop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baykeshop/apps/badmin/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :models.py
@说明    :后台菜单管理
@时间    :2023/07/16 10:14:45
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission, Group
from django.utils.translation import gettext_lazy as _

from baykeshop.conf import bayke_settings
from baykeshop.common.models import BaseModelMixin
from baykeshop.common.validators import validate_phone


class BaykeSiteMenus(BaseModelMixin):
    """ 后台管理菜单自定义 """
    name = models.CharField(_("名称"), max_length=50, unique=True)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    icon = models.CharField(_("图标"), max_length=50, blank=True, default="")
    permission = models.OneToOneField(
        Permission, 
        on_delete=models.CASCADE, 
        blank=True, 
        null=True,
        verbose_name=_("权限")
    )

    # TODO: Define fields here

    class Meta:
        ordering = ['-add_date']
        verbose_name = 'SiteMenus'
        verbose_name_plural = 'SiteMenus'

    def __str__(self):
        return self.name


class BaykeFrontedMenus(BaseModelMixin):
    """ 前后端分离管理菜单 """
    name = models.CharField(_("名称"), max_length=50, unique=True)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, blank=True, null=True)
    path = models.CharField("path", max_length=100, blank=True, default="")
    component = models.CharField("组件", max_length=50, blank=True, null=True)
    meta = models.JSONField(blank=True, null=True, verbose_name="meta")
    redirect = models.CharField(
        "跳转地址", 
        max_length=50, 
        blank=True, 
        default="", 
        help_text="格式应为`/home`"
    )
    sort = models.PositiveSmallIntegerField("排序", default=1)

    # TODO: Define fields here

    class Meta:
        ordering = ['sort']
        verbose_name = 'BaykeFrontedMenus'
        verbose_name_plural = 'BaykeFrontedMenus'

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.meta:
            self.meta = {
                "title": self.name,
                "hidden": False,
                "affix": False,
                "icon": "menu",
                "type": "menu", # menu，button，iframe, link
                "hiddenBreadcrumb": False,
                "active": False,
                "color": "black",
                "fullpage": False
            }
        super().save(*args, **kwargs)


class BaykePermissionAction(BaseModelMixin):
    """Model definition for BaykePermissionAction."""
    class RequestMethod(models.TextChoices):
        GET = "GET", _("查看")
        POST = "POST", _("新增")
        PUT = "PUT", _("修改")
        PATCH = "PATCH", _("局部修改")
        DELETE = "DELETE", _("删除")
    
    permission = models.OneToOneField(Permission, on_delete=models.CASCADE, verbose_name=_("权限"))
    menus = models.ForeignKey(BaykeFrontedMenus, on_delete=models.CASCADE, verbose_name=_("菜单"), blank=True, null=True)
    apiname = models.CharField(_("api接口name"), max_length=50, blank=True, default="", help_text="url的name别名，用来反解url")
    request_method = models.CharField(choices=RequestMethod.choices, max_length=10, blank=True, default="GET")
    mark = models.CharField(_("备注"), max_length=150, blank=True, default="")
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykePermissionAction."""
        ordering = ['-add_date']
        verbose_name = 'BaykePermissionAction'
        verbose_name_plural = 'BaykePermissionActions'

    def __str__(self):
        """Unicode representation of BaykePermissionAction."""
        return self.permission.codename


class BaykeDepartment(BaseModelMixin):
    """Model definition for department."""
    name = models.CharField("名称", max_length=50)
    parent = models.ForeignKey(
        "self", 
        on_delete=models.CASCADE, 
        blank=True, 
        null=True, 
        verbose_name="上级部门"
    )
    mark = models.CharField("备注", max_length=150, blank=True, default="")
    sort = models.PositiveSmallIntegerField("排序", default=1)
    is_enable = models.BooleanField("启用状态", default=True)

    # TODO: Define fields here

    class Meta:
        """Meta definition for department."""
        ordering = ["-sort", "-add_date"]
        verbose_name = 'department'
        verbose_name_plural = 'departments'
        constraints = [
            # 一个总公司下不能有相同的部门
            models.UniqueConstraint("name", "parent", name="dept_name_parent_unique")
        ]

    def __str__(self):
        """Unicode representation of department."""
        return self.name


class BaykeUser(BaseModelMixin):
    """Model definition for BaykeUser."""
    
    class UserType(models.TextChoices):
        FRONTED = "FRONTED", _("前台用户")
        SYSTEM = "SYSTEM", _("后台用户")
    
    owner = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, verbose_name=_("用户"))
    name = models.CharField(_("姓名"), max_length=50)
    dept = models.ForeignKey(BaykeDepartment, on_delete=models.SET_NULL, verbose_name="归属部门", blank=True, null=True)
    phone = models.CharField("手机号", blank=True, null=True, max_length=11, validators=[validate_phone])
    user_type = models.CharField(choices=UserType.choices, default=UserType.SYSTEM, max_length=50, verbose_name=_("用户类型"))
    sex = models.PositiveSmallIntegerField(choices=((0, "未知"), (1, "男"), (2, "女")), default=0, verbose_name=_("性别"))
    about = models.CharField(_("简介"), max_length=150, default="我喜欢baykeshop这个程序！", blank=True)
    avatar = models.ImageField(_("头像"), upload_to="avatar/", max_length=200, blank=True, null=True)
    balance = models.DecimalField(_("余额"), max_digits=8, decimal_places=2, blank=True, default=0)
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeUser."""
        ordering = ["-add_date"]
        verbose_name = 'BaykeUser'
        verbose_name_plural = 'BaykeUsers'

    def __str__(self):
        """Unicode representation of BaykeUser."""
        return self.name


class BaykeRoles(BaseModelMixin):
    """Model definition for BaykeRoles."""
    
    class PermRange(models.IntegerChoices):
        ALL = 1, _("全部可见")
        OWNER = 2, _("本人可见")
        DEPTS = 3, _("所在部门可见")
        DEPT = 4, _("所在部门及子级可见")
        SELECT = 5, _("选择的部门可见")
        CUSTOM = 6, _("自定义数据权限")
        
    group = models.OneToOneField(Group, on_delete=models.CASCADE, verbose_name=_("权限组"))
    codename = models.CharField(_("角色标识"), max_length=50, unique=True)
    depts = models.ManyToManyField(BaykeDepartment, blank=True, verbose_name="数据权限-关联部门")
    menus = models.ManyToManyField(BaykeFrontedMenus, blank=True, verbose_name=_("菜单"))
    perm_range = models.IntegerField(choices=PermRange.choices, default=PermRange.ALL, verbose_name=_("权限范围"))
    dashboard_grid = models.JSONField(blank=True, default=list, verbose_name=_("控制台模块权限"), help_text="当dashboard值为0时才有用！")
    dashboard = models.PositiveSmallIntegerField(default=0, blank=True, verbose_name=_("控制台视图"))
    sort = models.IntegerField(default=0, verbose_name=_("排序"))
    status = models.BooleanField(default=True, verbose_name=_("状态"))
    remark = models.CharField(_("备注"), max_length=150, blank=True, default="")

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeRoles."""
        ordering = ["-sort"]
        verbose_name = 'BaykeRoles'
        verbose_name_plural = 'BaykeRoless'

    def __str__(self):
        """Unicode representation of BaykeRoles."""
        return self.codename


class BaykeDictKey(BaseModelMixin):
    """ 字典分类 """
    name = models.CharField(_("名称"), max_length=50)
    code = models.SlugField(_("字典名称"), max_length=50, unique=True)
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, blank=True, null=True, verbose_name=_("父级")
    )
    status = models.BooleanField(default=True, verbose_name=_("状态"))
    sort = models.PositiveIntegerField(default=1, verbose_name=_("排序"))
    
    # TODO: Define fields here

    class Meta:
        ordering = ['-sort']
        verbose_name = 'ByakeDictKey'
        verbose_name_plural = 'ByakeDictKeys'

    def __str__(self):
        return self.name
    
    
class BaykeDictValue(models.Model):
    """Model definition for BaykeDictValue."""
    name = models.CharField(_("名称"), max_length=50)
    key = models.CharField(_("值"), max_length=150)
    dic = models.ForeignKey(BaykeDictKey, on_delete=models.CASCADE, verbose_name=_("字典key"))
    status = models.BooleanField(default=True, verbose_name=_("状态"))
    sort = models.PositiveIntegerField(default=1, verbose_name=_("排序"))
    
    # TODO: Define fields here

    class Meta:
        ordering = ['-sort']
        verbose_name = 'BaykeDictValue'
        verbose_name_plural = 'BaykeDictValue'

    def __str__(self):
        return self.name


class BaykeImage(BaseModelMixin):
    """Model definition for BaykeImage."""
    img = models.ImageField(_("图片"), upload_to="upload/", max_length=200)
    sort = models.PositiveSmallIntegerField(default=1, verbose_name=_("排序"))
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeImage."""
        ordering = ['-sort']
        verbose_name = 'BaykeImage'
        verbose_name_plural = 'BaykeImages'

    def __str__(self):
        """Unicode representation of BaykeImage."""
        return self.img.name


class BaykeSystem(BaseModelMixin):
    """Model definition for BaykeSystem."""
    site_title = models.CharField(_("站点名称"), max_length=50, default="baykeshop商城系统")
    logo_url = models.URLField(_("logo地址"), max_length=200, blank=True, default="")
    extend_json = models.JSONField(_("扩展配置"), default=dict, blank=True, null=True)
    copyright = models.CharField(_("版权信息"), max_length=150, blank=True, default="baykeshop版权所有")

    # TODO: Define fields here

    class Meta:

baykeshop/apps/comment/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
# Create your models here.
from baykeshop.common.models import ContentTypeAbstract


class BaykeShopComment(ContentTypeAbstract):
    """ 模型的通用关系 """
    
    class CommentChoices(models.IntegerChoices):
        GOOD = 5, _('好评')
        SO = 3, _('中评')
        BAD = 1, _('差评')
        
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="用户")
    content = models.CharField("留言内容", max_length=200)
    reply = models.CharField("回复内容", max_length=200, blank=True, default="")
    comment_choices = models.PositiveSmallIntegerField(
        default=5,
        choices=CommentChoices.choices,
        verbose_name="评分"
    )

    class Meta:
        ordering = ['-add_date']
        verbose_name = 'BaykeShopComment'
        verbose_name_plural = 'BaykeShopComment'
        
    def __str__(self):
        return self.content

baykeshop/apps/shop/models/user.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from baykeshop.common.models import BaseModelMixin


class BaykeUserBalanceLog(BaseModelMixin):
    """ 用户余额变动表 """
    
    class BalanceChangeStatus(models.IntegerChoices):
        # 收支状态
        ADD = 1, _('增加')
        MINUS = 2, _('支出')
    
    class BalanceChangeWay(models.IntegerChoices):
        # 收支渠道或方式
        PAY = 1, _('线上充值')        
        ADMIN = 2, _('管理员手动更改') 
        SHOP = 3, _('余额抵扣商品')
    
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="用户")
    amount = models.DecimalField("金额", max_digits=15, decimal_places=2)
    change_status = models.PositiveSmallIntegerField(
        choices=BalanceChangeStatus.choices, 
        blank=True,
        null=True
    )
    change_way = models.PositiveSmallIntegerField(
        choices=BalanceChangeWay.choices, 
        default=BalanceChangeWay.ADMIN        # 默认为后台
    )

    class Meta:
        verbose_name = '余额明细'
        verbose_name_plural = verbose_name

    def __str__(self):
        return f"{self.owner.username}-{self.amount}"
    
    @classmethod
    def balance_queryset(cls, user):
        return cls.objects.filter(owner=user)
    
    @classmethod
    def add_sum_amount(cls, user):
        # 累计充值
        amount__sum = cls.balance_queryset(user).filter(change_status=1).aggregate(Sum('amount')).get('amount__sum')
        return amount__sum if amount__sum else 0
    
    @classmethod
    def minus_sum_amount(cls, user):
        # 累计消费
        amount__sum = cls.balance_queryset(user).filter(change_status=2).aggregate(Sum('amount')).get('amount__sum')
        return amount__sum if amount__sum else 0
    

class BaykeAddress(BaseModelMixin):
    """ 收货地址 """
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="用户")
    name = models.CharField("签收人", max_length=50)
    phone = models.CharField("手机号", max_length=11)
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    province = models.CharField(max_length=150, verbose_name="省")
    city = models.CharField(max_length=150, verbose_name="市")
    county = models.CharField(max_length=150, verbose_name="区/县")
    address = models.CharField(max_length=150, verbose_name="详细地址")
    is_default = models.BooleanField(default=False, verbose_name="设为默认")
    
    class Meta:
        verbose_name = "收货地址"
        verbose_name_plural = verbose_name
       
    def __str__(self):
        return f'{self.name} {self.address}'

baykeshop/models/comment.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :comment.py
@说明    :评价模型
@时间    :2023/05/06 12:09:40
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from . import base


class BaykeOrderComments(base.ContentTypeAbstract):
    """ 评论 """
    class CommentChoices(models.IntegerChoices):
        GOOD = 5, _('好评')
        SO = 3, _('中评')
        BAD = 1, _('差评')

    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="用户")
    content = models.CharField("留言内容", max_length=200)
    comment_choices = models.PositiveSmallIntegerField(
        default=5,
        choices=CommentChoices.choices,
        verbose_name="评分"
    )
    
    class Meta:
        ordering = ['-add_date']
        verbose_name = "商品评价"
        verbose_name_plural = verbose_name
        
    def __str__(self):
        return self.content

baykeshop/models/statis.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :statis.py
@说明    :站点统计相关
@时间    :2023/04/21 12:48:30
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

baykeshop/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :forms.py
@说明    :表单
@时间    :2023/05/01 21:20:28
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.flatpages.forms import FlatpageForm as BaseFlatpageForm

from baykeshop.tinymce import Tinymce
from baykeshop.conf import bayke_settings


class SearchForm(forms.Form):
    
    search = forms.CharField(
        max_length=32, 
        label="搜索", 
        widget=forms.TextInput(
            {
                'type': 'search', 
                'class': 'input',
                'placeholder': f'{bayke_settings.SEARCH_VALUE}'
            }
        ))


class LoginForm(AuthenticationForm):
    """ 登录表单 """
    username = UsernameField(
        widget=forms.TextInput(attrs={
            "autofocus": True, 
            "class": "input", 
            "placeholder":" 请输入用户名..."
        }))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password", 
            "class": "input", 
            "placeholder":" 请输入密码..."
        }),
    )
    

class FlatpageForm(BaseFlatpageForm):
    
    class Meta(BaseFlatpageForm.Meta):
        widgets = {
            'content': Tinymce(),
        }

baykeshop/templates/baykeshop/user/address.html
{% extends 'baykeshop/user/menmber.html' %}


{% block menmber_title %}我的地址{% endblock %}

{% block menmber %}
{% include 'baykeshop/user/comp/address.html' with update=True delete=True %}
{% endblock %}

baykeshop/templates/baykeshop/user/balance.html
{% extends 'baykeshop/user/menmber.html' %}

{% block menmber_title %}我的余额{% endblock %}

{% block menmber %}
<div class="box is-radiusless is-shadowless">
    <div class="columns pl-6 pr-6 pt-3">
        <div class="column">
            <p class=" has-text-grey-light">账户可用余额</p>
            <h1 class="is-size-4">¥ {{ request.user.baykeuser.balance }}</h1> 
        </div>
        <div class="column">
            <p class=" has-text-grey-light">累计充值</p>
            <h1 class=" is-size-4">¥ {{ addplus }}</h1>
        </div>
        <div class="column">
            <p class=" has-text-grey-light">累计消费</p>
            <h1 class=" is-size-4">¥ {{ minusplus }}</h1>
        </div>
    </div>
    <div class=" dropdown-divider"></div>

    <div class="table-container pl-4 pr-4">
        <table class="table is-fullwidth is-hoverable">
            <tbody>
                {% for balance in baykeuserbalancelog_set %}
                <tr>
                    <td class="{% if balance.change_status == '增加' %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.change_status }}
                    </td>
                    <td class="{% if balance.change_status == '增加' %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {% if balance.change_status == '增加' %}  + {% else %} - {% endif %}{{ balance.amount }}
                    </td>
                    <td class="{% if balance.change_status == '增加' %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.change_way }}
                    </td>
                    <td class="{% if balance.change_status == '增加' %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.add_date }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>

    </div>

</div>
{% endblock %}

baykeshop/templates/baykeshop/user/login.html
{% extends 'baykeshop/base_site.html' %}

{% load i18n %}

{% block title %}登录{% endblock %}


{% block container %}

    <div class="is-flex is-flex-direction-column is-align-items-center is-justify-content-center" style="min-height: 800px;">
        <div class="box p-6 login-box">
            <p class="subtitle has-text-centered">
            {% block login_title %}登录{% endblock %}
            </p>
            <h1 class="title is-size-3 has-text-centered">baykeShop</h1>
            <div class="dropdown-divider"></div>
            
            {% block form %}
            <form action="" method="post">
              {% if form.errors and not form.non_field_errors %}
              <article class="message is-danger">
                <div class="message-body">
                  {% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
                </div>
              </article>
              {% endif %}
              
              {% if form.non_field_errors %}
              <article class="message is-danger">
                <div class="message-body">
                  {% for error in form.non_field_errors %}
                  <p> {{ error }}</p>
                  {% endfor %}
                </div>
              </article>
              {% endif %}
              {% csrf_token %}
              <div class="field">
                <p class="control has-icons-left has-icons-right">
                  {{ form.username }}
                  <span class="icon is-small is-left">
                    <i class="mdi mdi-account"></i>
                  </span>
                  <span class="icon is-small is-right">
                    <i class="mdi mdi-check"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <p class="control has-icons-left">
                  {{ form.password }}
                  <span class="icon is-small is-left">
                    <i class="mdi mdi-lock"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <p class="control">
                  <a href="{% url 'baykeshop:register' %}" class="is-size-7">还没有账号？立即注册！</a>
                </p>
              </div>
              <div class="field">
                <p class="control">
                  <input class="button is-primary is-fullwidth" type="submit" value="登录">
                </p>
              </div>
            </form>
            {% endblock %}
        </div>
    </div>
{% endblock %}

baykeshop/templates/baykeshop/user/logout.html
{% extends 'baykeshop/user/login.html' %}


{% block login_title %}您已登出{% endblock %}
{% block form %}
<div class="has-text-centered">
    <p>感谢您与本站今天度过的美好时光...</p>
    <div class="buttons is-justify-content-center mt-4">
        <a class="button is-primary is-small is-light" href="{% url 'baykeshop:login' %}">
            <span class="mdi mdi-login-variant"></span>
            重新登录
        </a>
        <a class=" button is-success is-small is-light" href="{% url 'baykeshop:home' %}">
            <span class="mdi mdi-keyboard-return"></span>
            返回首页
        </a>
    </div>
</div>
{% endblock %}

baykeshop/templates/baykeshop/user/menmber.html
{% extends 'baykeshop/base_site.html' %}

{% load static %}

{% block title %}
{{ request.user.username }} - 个人中心    
{% endblock %}

{% block breadcrumb %}
<div class="container">
  <nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'baykeshop:home' %}">首页</a></li>
      <li class="is-active"><a href="#" aria-current="page">个人中心</a></li>
    </ul>
  </nav>
</div>
{% endblock %}

{% block container %}
<div class="container">
    <div class="columns">
        <div class="column is-2">
            <div class="box is-radiusless is-marginless is-flex is-flex-direction-column is-align-items-center">
                <figure class="image is-64x64">
                    <img class="is-rounded" src="{{ request.user.baykeuser.avatar.url }}" >
                </figure>
                <p class="mt-2">
                    {% if request.user.baykeuser.nickname %}
                        {{ request.user.baykeuser.nickname }}
                    {% else %}
                        {{ request.user.username }}
                    {% endif %}
                </p>
            </div>

            <div class="box is-radiusless">
                <aside class="menu">
                    <p class="menu-label">
                      账户管理
                    </p>
                    <ul class="menu-list">
                      <li><a href="{% url 'baykeshop:menmber' request.user.id %}" class="{% if active == 'menmber' %} is-active {% endif %}">个人信息</a></li>
                      <li><a href="{% url 'baykeshop:balance' request.user.id %}" class="{% if 'balance' in request.path %} is-active {% endif %}">我的余额</a></li>
                      <li><a href="{% url 'baykeshop:menmber-address' %}" class="{% if 'address' in request.path %} is-active {% endif %}">地址管理</a></li>
                    </ul>
                    <p class="menu-label">
                      订单管理
                    </p>
                    <ul class="menu-list">
                      <li><a href="{% url 'baykeshop:menmber-orders' %}" class="{% if 'order' in request.path %} is-active {% endif %}">我的订单</a></li>
                    </ul>

                </aside>
            </div>

        </div>

        <div class="column">
            <div class="box is-radiusless">
                <h1 class="is-size-4">
                {% block menmber_title %}个人中心{% endblock %}
                </h1>
                <div class="dropdown-divider"></div> 
                {% block menmber %} 
                <div class="columns pt-3 pb-3">
                    <div class=" column is-2">个人信息</div>
                    {% include 'baykeshop/user/comp/userinfo.html' %}
                </div>
                {% endblock %}
            </div>
        </div>

    </div>
</div>

{% endblock %}